name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      # - name: Install yarn (for act)
      #   run: npm install --global yarn
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Base Setup
      #   uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      # - name: Check Release
      #   uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # # - name: Upload Distributions
      # #   uses: actions/upload-artifact@v3
      # #   with:
      # #     name: jupyterlab-box-drive-releaser-dist-${{ github.run_number }}
      # #     path: .jupyter_releaser_checkout/dist
